### DISCUSSION TITLE
Can't define api_keys in spacefile

### DISCUSSION THREAD

**Discussion by AndreWohnsland** [deta/cloud-docs#759] [Help] [answered]
When I try to define the api_keys argument under presets for a micro in the space file, I get:

```
Error: failed to do parse spacefile file, please check for correct syntax: yaml: unmarshal errors:
  line 9: field api_keys not found in type shared.Presets
```
 
Using following file:

```
# Spacefile Docs: https://go.deta.dev/docs/spacefile/v0
v: 0
micros:
  - name: fastapi-yay
    primary: true
    src: .
    engine: python3.9
    presets:
      api_keys: true
```

It's the same as in [the Docs](https://deta.space/docs/en/basics/micros#api-keys), and I've just installed the space CLI yesterday, so I think I am on the latest version.

Any idea what needs to be changed to get api_keys working?
